api_platform:
    title: "Calculator of currencies between SGD and PLN"
    description: "Simple caltulator that will allow to get really nice job :) "
    version: 1.1.1
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
